name: Update Credly Badges

on:
#   schedule:
    # - cron: '0 0 * * *' # Runs daily at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Update Credly Badges
        uses: jd-35656/readme-credly-badges@v1
        with:
          credly_username: 'Sharon-Krochkovich'
          github_token: ${{ secrets.GITHUB_TOKEN }}